Changes for ARM

diff --git a/mkefi b/mkefi
--- a/mkefi
+++ b/mkefi
@@ -1,24 +1,46 @@
 #!/bin/bash
 set -e
+shopt -s nullglob
+
+: "${ARCH:=$(uname -m)}"
+case "$ARCH" in
+	x86_64) efiarch=x64 ;;
+	aarch64) efiarch=aa64 ;;
+	*) echo "unknown arch $ARCH" >&2; exit 1 ;;
+esac
 : "${kv:=$(uname -r)}"
 : "${pfx:=/usr/lib/systemd}"
-: "${sdboot:=$pfx/boot/efi/systemd-bootx64.efi}"
-: "${sdstub:=$pfx/boot/efi/linuxx64.efi.stub}"
+: "${sdboot:=$pfx/boot/efi/systemd-boot$efiarch.efi}"
+: "${sdstub:=$pfx/boot/efi/linux$efiarch.efi.stub}"
+: "${cmdline:=verbose console=ttyS0 console=tty}"
+# "${keyfile:=private.pem}"
+
+for i in vmlinuz Image; do
+	kernel="/lib/modules/$kv/$i"
+	[ -e "$kernel" ] || continue
+	break
+done
+if ! [ -e "$kernel" ]; then
+	echo "$kernel not found. Set \$kv to one of the following versions:"
+	echo /lib/modules/*/{vmlinz,Image}
+	exit 1
+fi
 
 rm -rf efi
+
+read -r token < /etc/machine-id
+
 mkdir -p efi/EFI/BOOT
 mkdir -p efi/EFI/Linux
 
-read -r token < /etc/machine-id
 dst=efi/EFI/Linux/"$token-$kv.efi"
-
-cp "$sdboot" efi/EFI/BOOT/BOOTX64.EFI
+cp "$sdboot" efi/EFI/BOOT/BOOT${efiarch^^}.EFI
 
 /usr/lib/systemd/ukify build \
 	--stub="$sdstub" \
-	--linux=/usr/lib/modules/"$kv"/vmlinuz \
+	--linux="$kernel" \
 	--initrd=initrd \
-	--cmdline="verbose console=ttyS0 console=tty" \
+	--cmdline="${cmdline}" \
 	--splash=splash.bmp \
 	--output "$dst"
 
@@ -52,3 +74,5 @@ cd "$dst.extra.d"
 	done
 
 cd -
+
+: > efi-stamp
diff --git a/mkinitrd b/mkinitrd
--- a/mkinitrd
+++ b/mkinitrd
@@ -1,7 +1,10 @@
 #!/bin/bash
 set -e
-dest="d"
+o="${1:-initrd-busybox}"
+dest="$o.d"
 rm -rf "$dest"
+
+umask 022
 
 mkdir -p "$dest"/usr/{bin,sbin,lib,lib64}
 mkdir -p "$dest"/{etc,dev,proc,sys,run,var,sysroot,tmp}
@@ -14,17 +17,18 @@ ln -s usr/lib64 "$dest"
 cat <<'EOF' > "$dest"/etc/initrd-release
 NAME="busybox"
 ID="busybox"
-ID_LIKE="opensuse suse"
 ANSI_COLOR="0;32"
 EOF
 
-install /usr/bin/busybox-static "$dest/usr/bin"
-ln "$dest/usr/bin/busybox-static" "$dest/usr/bin/sh"
-ln "$dest/usr/bin/busybox-static" "$dest/usr/bin/mount"
+busybox=/usr/bin/busybox
+[ -e "$busybox-static" ] && busybox="$busybox-static"
+install "$busybox" "$dest/usr/bin"
+ln "$dest$busybox" "$dest/usr/bin/sh"
+ln "$dest$busybox" "$dest/usr/bin/mount"
 mkdir -p "$dest/usr/lib/busybox"
 while read -r file; do
-	ln "$dest/usr/bin/busybox-static" "$dest/usr/lib/busybox/$file"
-done < <(busybox-static --list)
+	ln "$dest$busybox" "$dest/usr/lib/busybox/$file"
+done < <("$busybox" --list)
 cat > "$dest/etc/profile" <<'EOF'
 #!/bin/sh
 # fallback to busybox tools
@@ -34,16 +38,38 @@ EOF
 
 cat > "$dest/init" <<'EOF'
 #!/bin/sh
-echo "executed $0"
+echo "executed initrd $0"
 if [ "$$" = 1 ] && ! [ -e /proc/1 ]; then
 	mount -t proc proc /proc
 	mount -t devtmpfs devtmpfs /dev
 	mount -t sysfs sysfs /sys
 	mount -t tmpfs tmpfs /tmp
+	mount -t tmpfs tmpfs /run
 fi
 . /etc/profile
-exec /bin/sh -i < /dev/console > /dev/console 2>&1
+read -r cmdline < "${1:-/proc/cmdline}"
+for param in $cmdline; do
+	case "$param" in
+		root=*) root="${param#root=}" ;;
+	esac
+done
+case "$root" in
+	/*) ;;
+	UUID=*|LABEL=*) root="$(findfs "$root")"; echo "resolved root dev to $root" ;;
+	*) echo "ERROR: can't parse root fs parameter: $root" >&2; root= ;;
+esac
+if [ -z "$root" ] || grep -q rd.break /proc/cmdline; then
+	/bin/sh -i < /dev/console > /dev/console 2>&1
+fi
+mount "$root" /sysroot
+echo "switching root to $root"
+for i in proc dev sys tmp run; do
+	echo "moving $i"
+	mount --move /$i /sysroot/$i
+done
+exec switch_root /sysroot /sbin/init
 EOF
 chmod 755 "$dest/init"
 
-(cd "$dest"; find . -print0 | cpio --format newc --null -R root:root -o --quiet) > initrd-busybox
+(cd "$dest"; find . -print0 | cpio --format newc --null -R root:root -o --quiet) > "$o.new"
+mv "$o.new" "$o"
